language: scala
scala:
  - 2.10.2
  - 2.10.1
  - 2.10.0
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk6
  - openjdk6
branches:
  only:
    - master
before_install:
  - chmod +x ./gradlew
before_script:
  - psql -U postgres -c 'create database photon_persist_test;'
script:
  - ./gradlew check -Dphoton-persist.tests.db.driver="org.postgresql.Driver" -Dphoton-persist.tests.db.dsn="jdbc:postgresql://localhost/photon_persist_test?user=postgres"
